### ISSUE TITLE
Addons.xml and .xml.md5 must be in a repository

### ISSUE THREAD

**Issue by gzhytar** [xbmcrus/XBMC.ru-forum-Add-ons#6]
Seems that it was deleted in https://github.com/xbmcrus/XBMC.ru-forum-Add-ons/commit/a91b1644ea2b6d4227e1cba4a9a5525677715ffe and updated one was not generated. 

As a result Kodi repository is not functional for NEW clients

**Comment by seppius-xbmc-repo** [comment]
Это архивное репо. Здесь в основном старые "испорченные" аддоны, оставшиеся без поддержки. Не используйте это репо.
